# Send prefix
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix
 
# Use Alt-arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
 
# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window
 
# Mouse mode
setw -g mouse on

# Automatically renmae windows to the current directoy name
set-window-option -g window-status-format '#I:#(basename "#{pane_current_path}")#F'
set-window-option -g window-status-current-format '#I:#(basename "#{pane_current_path}")#F'
 
# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v
 
# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Enable true color support (24-bit RGB)
# this allows passthrough colors from tmux to wezterm to neovim
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",wezterm:RGB"

# Enable undercurl support (for better syntax highlighting)
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# Enable colored underline support (for diagnostics)
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
